spring:
  thymeleaf:
    prefix: classpath:/templates
    cache: false
  mvc:
    favicon:
      enabled: true
    locale: pt_BR
  h2.console:
    enabled: true
    path: /db
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
      #database-platform: org.hibernate.dialect.MySQLDialect
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverclassname: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catamusico?createDatabaseIfNotExist=true
    username: root
    password: 
    #url: jdbc:h2:~/dev;DB_CLOSE_ON_EXIT=FALSE
    #platform: h2
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
